src/Entity/Housing.php
<?php

namespace App\Entity;

use App\Repository\Housing\HousingRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=HousingRepository::class)
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity("address", message="Cette adresse est déjà prise, merci de la changer. !")
 */
class Housing
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private ?int $id = null;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(
     *     message = "Le champs adresse est obligatoire."
     * )
     * @Assert\Length(min=10, max=255, minMessage="l'adresse doit comporter au moins 10 charactères" )
     */
    private ?string $address = null;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank(
     * message = "Le champs étage est obligatoire."
     * )
     * @Assert\PositiveOrZero(
     *    message = "La valeur de l'étage ne peut pas être négative."
     * )
     */
    private ?int $floor = null;

    /**
     * @ORM\Column(type="boolean")
     */
    private ?bool $elevator = null;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private ?\DateTimeImmutable $updatedAt = null;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private ?\DateTimeImmutable $createdAt;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Url(
     *    message = "L'url '{{ value }}' n'est pas une url valide",
     * )
     */
    private ?string $mainPicture = null;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank(
     *     message = "Le champs nombre de pièces est obligatoire."
     * )
     * @Assert\PositiveOrZero(
     *    message = "La valeur ne peut pas être négative."
     * )
     */
    private ?int $room = null;

    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(?int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getElevator(): ?bool
    {
        return $this->elevator;
    }

    public function setElevator(bool $elevator): self
    {
        $this->elevator = $elevator;

        return $this;
    }

    public function getUpdateAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    /**
     * @ORM\PreUpdate
     */
    public function setupdatedAtValue(): self
    {
        $this->updatedAt = new \DateTimeImmutable();

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function getMainPicture(): ?string
    {
        return $this->mainPicture;
    }

    public function setMainPicture(?string $mainPicture): self
    {
        $this->mainPicture = $mainPicture;

        return $this;
    }

    public function getRoom(): ?int
    {
        return $this->room;
    }

    public function setRoom(?int $room): self
    {
        $this->room = $room;

        return $this;
    }
}

src/Form/Housing/HousingType.php
<?php

namespace App\Form\Housing;

use App\Entity\Housing;
use App\Form\FormTrait;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;

class HousingType extends AbstractType
{
    use FormTrait;

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('address', TextType::class, $this->setOptions("Indiquer l'adresse du bien"))
            ->add('floor', IntegerType::class, $this->setOptions("Renseigner l'étage", [
                'attr' => ["min" => 0]
            ]))
            ->add('room', IntegerType::class, $this->setOptions("Renseigner le nombre de pièces", [
                'attr' => ["min" => 0]
            ]))
            ->add('elevator', ChoiceType::class, $this->setOptions("Présence d'un ascenceur ? ", [
                "choices" => [
                    "Oui" => true,
                    "Non" => false
                ]
            ]))
            ->add('mainPicture', UrlType::class, $this->setOptions("Veuillez rentrer une url d'image", [
                "required" => false
            ]))
            ->add('submit', SubmitType::class, $this->setOptions('Sauvegarder'));
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Housing::class,
        ]);
    }
}

src/Controller/Housing/Listing.php
<?php

namespace App\Controller\Housing;

use App\Entity\Housing;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class Listing extends AbstractController
{

    /**
     * Show Housing details
     * @Route("/{id}/show", name="housing_show", requirements={"id": "\d+"}, methods="GET")
     *
     * @param Housing $housing
     * @return Response
     */
    public function show(Housing $housing): Response
    {
        return $this->render(
            "/housing/show.html.twig",
            [
            'housing' => $housing
            ]
        );
    }
}

src/Controller/Housing/Update.php
<?php

namespace App\Controller\Housing;

use App\Entity\Housing;
use App\Form\Housing\HousingType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Subscriber\Housing\Events\HousingEditEvent;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class Update extends AbstractController
{

    /**
     * @var EventDispatcherInterface $dispatcher
     */
    protected $dispatcher;

    /**
     * @param EventDispatcherInterface $dispatcher
     */
    public function __construct(EventDispatcherInterface $dispatcher)
    {
        $this->dispatcher = $dispatcher;
    }

    /**
     * Edition Housing
     * @Route("/{id}/edition", name="housing_edition", requirements={"id": "\d+"})
     *
     * @param Housing $housing
     * @param Request $request
     * @param EntityManagerInterface $em
     * @return Response
    */
    public function edit(
        Housing $housing,
        Request $request,
        EntityManagerInterface $em
    ): Response {
        $form = $this->createForm(HousingType::class, $housing)->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->flush();
            $this->addFlash("success", "Votre appartement à bien été mis à jour");

            // Create event edit housing
            $housingEvent = new HousingEditEvent($housing);
            $this->dispatcher->dispatch($housingEvent, HousingEditEvent::NAME);

            return $this->redirectToRoute(
                "housing_show",
                [
                'id' => $housing->getId()
                ]
            );
        }
        return $this->render("/housing/edit.html.twig", [
            'form' => $form->createView()
        ]);
    }
}

templates/housing/_card.html.twig
<div class="card mb-3">
	<img src={{(housing.mainPicture ? housing.mainPicture : "https://fakeimg.pl/800x800/?text=Maline" )}} alt="Image de {{housing.address}}" class="img-fluid" alt="image du logement">
	<div class="card-body">
		<span class="badge bg-primary">
			Créer le
			{{housing.createdAt | date("d/m/Y")}}
		</span>
		{% if housing.updateAt %}
			<p class="badge bg-info">
				Mise à jour le
				{{housing.updateAt| date("d/m/Y à H:i")}}
			</p>
		{% endif %}

		<div class="card-body">
			<h5 class="card-title">
				<i class="fas fa-map-marker-alt text-warning"></i>
				{{housing.address}}
			</h5>
			<p class="card-text">
				Nombre de pièces :
				{{housing.room}}
			</p>
			<p class="card-text">
				Étage :
				{{housing.floor}}
			</p>
			<p class="card-text">
				Ascenseur :
				{{(housing.elevator) ? "oui" : "non"}}
			</p>
		</div>


		<hr>
		<div>
			<a href="{{path('housing_show', {'id' : housing.id})}}" class="btn btn-primary btn-sm">
				Détails
			</a>
			<a href="{{path('housing_edition',{'id' : housing.id})}}" class="btn btn-success btn-sm">
				Editer
			</a>
		</div>
	</div>
</div>

templates/housing/_form.html.twig
{% block infos %}
	<div class="row">
		<div class="col-lg-4 col-md-12">
			{{ form_row(form.address) }}
		</div>
		<div class="col-lg-4 col-md-12">
			{{ form_row(form.room) }}
		</div>
		<div class="col-lg-4 col-md-12">
			{{ form_row(form.floor) }}
		</div>
	</div>
	<div class="row">
		<div class="col-lg-4 col-md-12">
			{{ form_row(form.elevator) }}
		</div>
		<div class="col-lg-6 col-md-12">
			{{ form_row(form.mainPicture) }}
		</div>
	</div>

{% endblock infos %}

{% block submit %}
	{{ form_row(form._token) }}

	<div class="row">
		<div class="col-12 text-center mt-3">
			{{ form_row(form.submit) }}
		</div>
	</div>
{% endblock submit %}

templates/housing/edit.html.twig
{% extends "base.html.twig" %}

{% block title %}
	Edition de l'appartement
{% endblock %}

{% block body %}
	{{ form_start(form) }}

	<div class="row">
		<div class="col-md-12 col-sm-12">
			<div class="row">
				<div class="col-12">
					<div class="card shadow mt-3">
						<div class="card-header d-flex align-items-center">
							<h6 class="m-0 font-weight-bold text-primary">
								Éditer les informations de l'appartement
							</h5>
						</div>
						<div class="card-body">
							{{ block("infos", "housing/_form.html.twig") }}

							{{ block("submit", "housing/_form.html.twig") }}
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	{{ form_end(form, {"render_rest": false}) }}
{% endblock %}

templates/housing/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Détails de l'appartement n°:
	{{housing.id}}
{% endblock %}
{% block body %}
	<H1>
		Détails de l'appartement n°:
		{{housing.id}}
	</H1>
	<div class="row">
		<div class="col-4">
			<img src={{housing.mainPicture ? housing.mainPicture : "https://fakeimg.pl/800x800/?text=Maline"}} alt="Image de {{housing.address}}" class=" img-fluid">
		</div>
		<div class="col">
			<span class="badge bg-primary">
				Créer le
				{{housing.createdAt | date("d/m/Y")}}
			</span>
			{% if housing.updateAt %}
				<p class="badge bg-info">
					Mise à jour le
					{{housing.updateAt| date("d/m/Y à H:i")}}
				</p>
			{% endif %}
			<p>
				Adresse de l'appartement :
				{{housing.address}}
			</p>
			<p class="card-text">
				Nombre de pièces :
				{{housing.room}}
			</p>
			<p class="card-text">
				Étage :
				{{housing.floor}}
			</p>
			<p class="card-text">
				Ascenseur :
				{{(housing.elevator) ? "oui" : "non"}}
			</p>
			<a href="{{path('housing_edition',{'id' : housing.id})}}" class="btn btn-success btn-sm">
				Editer
			</a>
		</div>
	</div>
{% endblock %}